name: Release Express app # Name of the workflow

# On a push to the branch named main
on:
  push:
    branches:
      - main

# Job called build runs-on ubuntu-latest
jobs:
  publish-docker-hub:
    name: Publish image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout to the repository
      - uses: actions/checkout@v4

      # We need to login so we can later push the image without issues.
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Builds keyxcode/littlelemon-pipeline
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: keyxcode/littlelemon-pipeline:latest
          secrets: |
            "DB_CONNECTION=${{ secrets.DB_CONNECTION }}"

  deploy:
    name: Deploy new image on Render
    runs-on: ubuntu-latest
    needs: publish-docker-hub
    steps:
      - name: Deploy
        # Only run this step if the branch is main
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
